#!/bin/bash

hash -r

usage(){
    ret=${1:-0}
    cat <<EoF
${0##*/} snapshot_name
EoF
    exit ${ret}
}

if [ $# -lt 1 ] ; then usage ; fi
name=$1
for s in bcpc-vm{1..3} ; do VBoxManage snapshot $s take $name --live ; done 
