#!/bin/bash

hash -r

usage(){
    ret=${1:-0}
cat <<EoF
${0##*/} nodename
EoF
    exit ${ret}
}

if [ $# -lt 1 ] ; then usage ; fi
nodename="$1"
d="$(date)"

set -e
dir="$(git rev-parse --show-toplevel)"
cd "${dir}/bootstrap/vagrant_scripts"
vagrant ssh -c "sudo date -s '$d'" $nodename
