#!/bin/bash
# Re-chefs a node
hash -r

DIR=$(cd ${0%%/*} && pwd -P)
export PATH=$DIR:$PATH

vagrant_dir=$DIR/../bootstrap/vagrant_scripts
pushd "${vagrant_dir}"

nodes=( $@ )
cookbooks=( bcpc bcpc-extra )
read -d %% cmd <<EoF
  cd chef-bcpc && knife role from file roles/*.json && \
    echo environments/Test-Laptop-Vagrant.json | xargs -tn1 knife environment from file && \
    knife cookbook upload -o cookbooks ${cookbooks[@]}
EoF
vagrant ssh -c "$cmd" vm-bootstrap
vagrant ssh -c 'sudo -i chef-client' vm-bootstrap
for node in "${nodes[@]}" ; do
  vagrant ssh -c 'sudo -i chef-client' $node -- -t
done
