# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright 2019, Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

base_box = "bento/ubuntu-18.04"

def setup_proxy(node)
  http_proxy  = ENV['http_proxy']  || ''
  https_proxy = ENV['https_proxy'] || ''
  if http_proxy != ''
    node.vm.provision "shell", path: "proxyconfig.sh",
     args: [http_proxy, https_proxy]
  end
end

# Create 3 TORs
Vagrant.configure(2) do |config|
  (1..3).each do |i|
    config.vm.define "tor#{i}" do |node|
      config.vm.provider "virtualbox" do |node|
        node.name = "tor#{i}"
        node.memory = 512
      end
      node.vm.box = base_box
      node.vm.box_download_insecure = true
      node.vm.network "private_network", virtualbox__intnet: "tor#{i}_spine1",
       auto_config: false
      node.vm.network "private_network", virtualbox__intnet: "tor#{i}_spine2",
       auto_config: false
      node.vm.network "private_network", virtualbox__intnet: "tor#{i}_hv",
       auto_config: false
      node.vm.network "private_network", virtualbox__intnet: "management#{i}",
       auto_config: false
      node.vm.network "private_network", virtualbox__intnet: "storage#{i}",
       auto_config: false
      setup_proxy(node)
      node.vm.provision "shell", path: "provisioner.sh", args: #{i}
      node.vm.hostname = "tor#{i}"
    end
  end

# Create 2 spines
  (1..2).each do |i|
    config.vm.define "spine#{i}" do |node|
      config.vm.provider "virtualbox" do |node|
        node.name = "spine#{i}"
        node.memory = 512
      end
      node.vm.box = base_box
      node.vm.box_download_insecure = true
      node.vm.network "private_network", virtualbox__intnet: "tor1_spine#{i}",
       auto_config: false
      node.vm.network "private_network", virtualbox__intnet: "tor2_spine#{i}",
       auto_config: false
      node.vm.network "private_network", virtualbox__intnet: "tor3_spine#{i}",
       auto_config: false
      setup_proxy(node)
      node.vm.provision "shell", path: "provisioner.sh", args: #{i}
      node.vm.hostname = "spine#{i}"
    end
  end
end
